### PR TITLE
Devss

### PR DESCRIPTION
**Pull request by PogromistDev**
Take screenshot of your pc's screen

### CODE REVIEW

**Comment by jonasgeiler** [comment]
not sure what this has to do with devRant?

**Comment by PogromistDev** [comment]
Devranters post their photo of pc from mobile devices. With this you can screenshot display and download to smartphone.

**Comment by cozyplanes** [comment]
Doesn't seem anything related to devrant

You mean something like Signal is related to devrant since few devranters are using it

**Comment by PogromistDev** [comment]
So many devRanters upload to devrant photograph of their monitor (i can't count how much) instead of screenshotting it. Don't you all not understand it? it's very related.

**Comment by cozyplanes** [comment]
> So many devRanters upload to devrant photograph of their monitor (i can't count how much) instead of screenshotting it. Don't you all not understand it? it's very related.

If you wondered why people are taking pics of their desks, either in office or remote, here's why: https://www.instagram.com/devdesks/

**Comment by PogromistDev** [comment]
> > So many devRanters upload to devrant photograph of their monitor (i can't count how much) instead of screenshotting it. Don't you all not understand it? it's very related.
> 
> If you wondered why people are taking pics of their desks, either in office or remote, here's why: https://www.instagram.com/devdesks/

to show screen not their setup :|

**Comment by cozyplanes** [comment]
> to show screen not their setup :|
I will leave the decision to @Skayo

**Comment by PogromistDev** [comment]
Instead of this  i can post this

**Comment by jonasgeiler** [comment]
I'll count it as a "tool for devRant"

**Pull request merged**
